# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiveStream' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LiveStream
pod 'AFNetworking'
pod 'SDWebImage', '~> 3.7.3'
pod 'Masonry'
pod 'MBProgressHUD'
pod 'Reachability'
pod 'LFLiveKit'
  target 'LiveStreamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LiveStreamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
